### ISSUE TITLE
cant compile. 

### ISSUE THREAD

**Issue by tr0yspradling** [coxley/dotfiles#1]
yousuck.cpp:8:39: fatal error: my/big/toaster.ld: instructions not clear. **** stuck in linker.

**Comment by tr0yspradling** [comment]
Please escalate this to the appropriate teams

**Comment by tr0yspradling** [comment]
This is critical

**Comment by calhill** [comment]
Same issue. Please escalate.

**Comment by coxley** [comment]
wontfix. reporters are suspect.

**Comment by Dnida** [comment]
How do use this one windows? pls reopen issue.
